language: node_js
node_js:
  - "10"
cache: npm

notifications:
  email:
    recipients:
      - cristmactavish@outlook.com # 设置通知邮件
    on_success: change
    on_failure: always

install:
  - npm install -g gitbook-cli
  - gitbook install

script:
  - gitbook build

after_script:
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
  - git push --force --quiet "https://${TOKEN}@${REF}" gh-pages

branches:
  only:
    - gh-pages

env:
  global:
    - REF=github.com/gonearewe/EasyTesting.git # 设置 github 地址
