# config file for gormt(https://github.com/xxjwxc/gormt), the mysql database to golang struct conversion tool.
out_dir: "./models"  # out dir
url_tag: json # web url tag(json,db(https://github.com/google/go-querystring))
language:  # language(English,中 文)

db_tag: gorm # DB tag(gorm,db)
simple: false #simple output
is_out_sql: false # Whether to output sql
is_out_func: false # Whether to output function
is_foreign_key: false # Whether to mark foreign key or not
is_gui: false # Whether to operate on gui
is_table_name: true # Whether to out GetTableName/column function
is_null_to_point: true # database is 'DEFAULT NULL' then set element type as point

is_web_tag: true # JSON tag for struct fields
is_web_tag_pk_hidden: false
web_tag_type: 1 # json tag 0: Small Camel-Case 1: snake_case

table_prefix: "" #table prefix
table_names: "" # Specified table generation, multiple tables with , separated
is_column_name: false # Whether to generate column names
is_out_file_by_table_name: true # Whether to generate multiple models based on table names

db_info:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "12345"
  database: "easy_testing"
  type: 0 # database type (0:mysql , 1:sqlite , 2:mssql)

self_type_define: # Custom data type mapping
  datetime: time.Time
  date: time.Time
out_file_name: "" # Custom build file name