# 服务端软件的配置文件，应当与程序放在同一级目录下，不支持热重载，修改后需要重启程序才能生效
enable_console_color: false # console 输出是否使用颜色，如果日志输出到文件，控制颜色的字符会变成乱码
dsn: "root:12345@tcp(127.0.0.1:3306)/easy_testing?charset=utf8mb4&parseTime=True&loc=Local" # 数据库 DSN
port: 9345 # 服务器监听的端口
jwt_secret_key: "4xg8jlAh8s00KR1Fdc6mY" # JWT 使用的密钥，建议正式部署时修改它
log_file_name: "debug.log" # 日志文件的名字，文件将位于执行程序目录（或其快捷方式目录）下；日志会在 stdout 和文件中同步出现